---
- name: Docker | Setup storage
  include: "storage/{{ docker_storage_driver }}.yml"
  when: docker_storage_driver is defined

- name: Docker | Installation
  include: "pkgmgr/{{ ansible_pkg_mgr }}.yml"

- name: Docker | Configuration
  include: configuration/configuration.yml

- name: Docker | Proxy configuration
  include: proxy/proxy.yml
  when: docker_http_proxy is defined or
        docker_https_proxy is defined or
        docker_no_proxy_params is defined

- name: Docker | Ensure Docker service is enabled and started
  service:
    name: docker
    enabled: yes
    state: started
  when: ansible_distribution != "Fedora"

- name: Docker | Ensure Docker service is enabled and started (Fedora)
  shell: systemctl enable docker && systemctl start fedora
  when: ansible_distribution == "Fedora"

- name: Docker | Compose
  include: docker-compose/compose.yml
  when: docker_compose
