---
- name: Docker | EE | Check Requirements
  fail:
    msg: "Variable docker_ee_url is required and is not defined."
  when:
    - docker_ee_url is not defined
    - docker_edition == "ee"

- name: Docker | Setup storage
  include: "storage/{{ docker_storage_driver }}.yml"
  when: docker_storage_driver is defined

- name: Docker | Installation
  include: "{{ docker_edition }}/{{ ansible_pkg_mgr }}.yml"

- name: Docker | Ensure service starts at boot
  service:
    name: docker
    enabled: yes

- name: Docker | Configuration
  include: configuration.yml

- name: Docker | Proxy configuration
  include: proxy.yml
  when: docker_http_proxy is defined or
        docker_https_proxy is defined or
        docker_no_proxy_params is defined

- name: Docker | Ensure service started
  service:
    name: docker
    state: started
