---
- name: Docker | Proxy | Ensure docker.service.d folder is created
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Docker | Proxy | Ensure Docker service params are in place
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify:
    - Docker | Daemon-reload
    - Docker | Restart Docker
