---
- name: Docker | EE | YUM | Store Docker EE repository URL
  copy:
    content: "{{ docker_ee_url }}"
    dest: /etc/yum/vars/dockerurl

- name: Docker | EE | YUM | Ensure yum-utils is installed
  yum:
    name: yum-utils

- name: Docker | EE | YUM | Ensure Docker repo is ready
  shell: "yum-config-manager --add-repo {{ docker_ee_url }}/docker-ee.repo"
  creates: /etc/yum.repos.d/docker-ee.repo

- name: Docker | EE | YUM | Perform specific os tasks
  include: "os/{{ ansible_distribution | lower }}.yml"

- name: Docker | EE | YUM | Ensure deprecated docker packages are removed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - container-selinux
    - docker-engine-selinux
    - docker-engine
    - docker-ce

- name: Docker | EE | YUM | Ensure Docker package is installed
  yum:
    name: docker-ee
    state: present
    update_cache: yes
  notify: Docker | Restart Docker
