---
- name: Docker | CE | Debian | Ensure all APT prerequisites are met
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
