---
- name: Docker | DNF | Ensure dnf-plugins-core is installed
  dnf:
    name: dnf-plugins-core

- name: Docker | DNF | Ensure Docker repo is ready
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Docker | DNF | Ensure edge repository is enabled
  yum_repository:
    name: docker-ce-edge
    description: "Docker CE Edge - $basearch"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/edge"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    file: docker-ce
  when: docker_channel == "edge"
  notify:  Docker | CE | Upgrade to Edge

- name: Docker | DNF | Perform specific os tasks
  include: "os/{{ ansible_distribution | lower }}.yml"

- name: Docker | DNF | Ensure deprecated docker packages are removed
  dnf:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: Docker | DNF | Ensure Docker package is installed
  dnf:
    name: docker-ce
    state: present
  notify: Docker | Restart Docker
