---
- name: Docker | Daemon-reload
  shell: systemctl daemon-reload

- name: Docker | Restart Docker
  service:
    name: docker
    state: restarted

- name: Docker | Upgrade to Edge
  package:
    name: docker-ce
    state: latest
