---
- name: Docker | CE | YUM | Ensure yum-utils is installed
  yum:
    name: yum-utils

- name: Docker | CE | YUM | Ensure Docker repo is ready
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Docker | CE | YUM | Ensure edge repository is enabled
  yum_repository:
    name: docker-ce-edge
    description: "Docker CE Edge - $basearch"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/edge"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    file: docker-ce
  when: docker_channel == "edge"
  notify:  Docker | CE | Upgrade to Edge

- name: Docker | CE | YUM | Perform specific os tasks
  include: "os/{{ ansible_distribution | lower }}.yml"

- name: Docker | CE | YUM | Ensure deprecated docker packages are removed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - container-selinux
    - docker-engine-selinux
    - docker-engine
    - docker-ce

- name: Docker | CE | YUM | Ensure Docker package is installed
  yum:
    name: docker-ce
    state: present
    update_cache: yes
  notify: Docker | Restart Docker
