- name: Docker | Storage Driver | Btrfs | Debian | Ensure Btrfs package is installed
  apt:
    name: btrfs-tools
    state: present
  when: ansible_os_family == "Debian"

- name: Docker | Storage Driver | Btrfs | RedHat | Ensure Btrfs package is installed
  yum:
    name: btrfs-progs
    state: present
  when: ansible_os_family == "RedHat"

- name: Docker | Storage Driver | Btrfs | Ensure Btrfs driver is enabled
  modprobe:
    name: btrfs
    state: present

- name: Docker | Storage Driver | Btrfs | Ensure Btrfs storage filesystem is created
  filesystem:
    dev: "{{ docker_block_device }}"
    fstype: btrfs

- name: Docker | Storage Driver | Btrfs | Ensure /var/lib/docker folder is created
  file:
    dest: /var/lib/docker
    state: directory

- name: Docker | Storage Driver | Btrfs | Mount the filesystem
  mount:
    dest: /var/lib/docker
    src: "{{ docker_block_device }}"
    fstype: btrfs
    passno: '0'
    opts: "{{ docker_mount_opts | default(omit) }}"
    state: mounted
