---
- name: Docker | Storage Driver | devicemapper | Ensure LVM2 package is installed
  package:
    name: lvm2
    state: present

- name: Docker | Storage Driver | devicemapper | Ensure logical volume group is configured
  lvg:
    vg: docker
    pvs: "{{ docker_block_device }}"

- name: Docker | Storage Driver | devicemapper | Ensure thinpool volume is created
  lvol:
    vg: docker
    lv: thinpool
    size: 95%VG
    opts: "--wipesignatures y"
  register: thinpool

- name: Docker | Storage Driver | devicemapper | Ensure thinpoolmeta volume is created
  lvol:
    vg: docker
    lv: thinpoolmeta
    size: 1%VG
    opts: "--wipesignatures y"

- name: Docker | Storage Driver | devicemapper | Ensure volumes are converted to thinpool
  shell: lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
  when: thinpool.changed

- name: Docker | Storage Driver | devicemapper | Ensure autoextension of thin pools via 'lvm' profile is configured
  copy:
    src: docker-thinpool.profile
    dest: /etc/lvm/profile/docker-thinpool.profile
  register: docker_thinpool_profile
  notify: Docker | Restart Docker

- name: Docker | Storage Driver | devicemapper | Ensure 'lvm' profile is applied
  shell: lvchange --metadataprofile docker-thinpool docker/thinpool
  when: docker_thinpool_profile.changed

- name: Docker | Storage Driver | devicemapper | Ensure /var/lib/docker is created
  file:
    path: /var/lib/docker
    state: directory

- set_fact:
    docker_storage_opts:
      - "dm.thinpooldev=/dev/mapper/docker-thinpool"
      - "dm.use_deferred_removal=true"
      - "dm.use_deferred_deletion=true"
  when: docker_storage_opts is undefined
